### ISSUE TITLE
setState() called after dispose(): _TransitionToImageState#2d6c7(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)

### ISSUE THREAD

**Issue by skybur** [mchome/flutter_advanced_networkimage#50]
Hello, I'm having this error in console log. I'm using TransitionToImage in a ListView, when scrolling the listview, this error is printed in log.
Here is full stacktrace:
```
E/flutter ( 5765): setState() called after dispose(): _TransitionToImageState#8ea9f(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter ( 5765): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 5765): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 5765): 0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1103:9)
E/flutter ( 5765): 1      State.setState (package:flutter/src/widgets/framework.dart:1129:6)
E/flutter ( 5765): 2      _TransitionToImageState._updateImage.<anonymous closure> (package:flutter_advanced_networkimage/transition_to_image.dart:275:11)
E/flutter ( 5765): 3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter ( 5765): 4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter ( 5765): 5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter ( 5765): 6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter ( 5765): 7      Future._complete (dart:async/future_impl.dart:476:7)
E/flutter ( 5765): 8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 5765): 9      _futurize.<anonymous closure> (dart:ui/painting.dart:3895:17)
E/flutter ( 5765): 10     Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1531:17)
```

**Comment by mchome** [comment]
Hi, what version of this package you are using?
I cant reproduce this error.

**Comment by skybur** [comment]
I'm using version 0.3.12. I don't know if this is caused by my code or the plugin. Lemme try to create sample code from fresh project.

**Comment by skybur** [comment]
Here is the sample code
```
import 'package:flutter/material.dart';
import 'package:flutter_advanced_networkimage/flutter_advanced_networkimage.dart';
import 'package:flutter_advanced_networkimage/transition_to_image.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CustomScrollView(slivers: [
        SliverList(
            delegate: SliverChildListDelegate(List.generate(30, (i) {
          var img = 'https://picsum.photos/1280/768/?random';
          if (i < 10) {
            img = 'https://www.w3schools.com/w3css/img_ligghts.jpg';
          }
          return TransitionToImage(
            AdvancedNetworkImage(img, retryLimit: 1),
            placeholder: Image.asset('assets/placeholder.jpg'),
            height: 128,
            fit: BoxFit.cover,
          );
        }))),
      ]),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
and here is placeholder.jpg, placed in assets folder in the project root
![placeholder](https://user-images.githubusercontent.com/11155424/49846540-44a53b80-fdfe-11e8-854f-ffa264b0f2f7.jpg)

How to reproduce:
1. Run App.
2. Let the placeholder image loads (the first 10 image should 404)
3. Scroll to the bottom of list.
4. Scroll back to the top, the placeholder image should be missing (leaving blank spaces)
5. After a while, the error will be printed to the console

**Comment by mchome** [comment]
Try `v0.3.13`.

**Comment by skybur** [comment]
> 
> 
> Try `v0.3.13`.

It still happened.

**Comment by shoxter** [comment]
This is happening to me too. Basically when a ListView recycles the Widget, it throws an error because TransitionToImage is calling setSTate after being disposed of.

**Comment by shoxter** [comment]
Update: This is fixed in 0.3.13. Just tried it.

**Comment by skybur** [comment]
> 
> 
> Update: This is fixed in 0.3.13. Just tried it.

Hmm weird, I just tried it again with the sample code I provided above and it's still happening. However in my app it didn't happen.
